-- ============================================================================
-- Brixpense — revert in-app auth migration, restore magic-link RLS
-- ============================================================================
-- Correction migration. 20260512q assumed approvals would happen in-app
-- under authenticated session. The actual design is:
--
--   Expense:         no approval at all — auto-approved on submit
--   Purchase Req:    magic-link email to an approver chosen by the submitter
--                    from the manager_emails list (ops.expense_settings).
--                    The approver opens the link (no login required), signs,
--                    decides. This needs anon RLS gated on approval_token.
--
-- This migration:
--   1. Drops the self / manager UPDATE policies introduced by 20260512q.
--   2. Restores the original submitter-only UPDATE policy.
--   3. Recreates the 5 anon RLS policies the magic-link flow needs.
--   4. Removes the DEPRECATED comment from approval_token.
-- ============================================================================

-- ── 1. Drop the in-app auth UPDATE policies ────────────────────────────────
DROP POLICY IF EXISTS expense_requests_update_self    ON ops.expense_requests;
DROP POLICY IF EXISTS expense_requests_update_manager ON ops.expense_requests;


-- ── 2. Restore the original submitter-only UPDATE policy ───────────────────
DROP POLICY IF EXISTS expense_requests_update ON ops.expense_requests;
CREATE POLICY expense_requests_update ON ops.expense_requests
  FOR UPDATE TO authenticated
  USING (submitted_by = auth.uid());


-- ── 3. Restore anon RLS gated on approval_token (magic-link path) ──────────
-- Allow anon to read a request by approval_token (the approval page renders
-- the request details for the manager who clicked the magic link).
DROP POLICY IF EXISTS expense_requests_anon_select ON ops.expense_requests;
CREATE POLICY expense_requests_anon_select ON ops.expense_requests
  FOR SELECT TO anon USING (approval_token IS NOT NULL);

-- Allow anon to update status by approval_token (the decide function uses
-- this to flip the request to approved/denied without a Supabase session).
DROP POLICY IF EXISTS expense_requests_anon_update ON ops.expense_requests;
CREATE POLICY expense_requests_anon_update ON ops.expense_requests
  FOR UPDATE TO anon USING (approval_token IS NOT NULL);

-- Attachments — anon can read receipts for requests carrying a live token.
DROP POLICY IF EXISTS attachments_anon_select ON ops.expense_request_attachments;
CREATE POLICY attachments_anon_select ON ops.expense_request_attachments
  FOR SELECT TO anon USING (
    EXISTS (
      SELECT 1 FROM ops.expense_requests
      WHERE id = request_id AND approval_token IS NOT NULL
    )
  );

-- Approvals — anon can insert (the decide function writes the audit row) and
-- read (so the approval page can confirm a decision has been recorded).
DROP POLICY IF EXISTS approvals_insert_anon ON ops.expense_approvals;
CREATE POLICY approvals_insert_anon ON ops.expense_approvals
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS approvals_anon_select ON ops.expense_approvals;
CREATE POLICY approvals_anon_select ON ops.expense_approvals
  FOR SELECT TO anon USING (true);


-- ── 4. Un-deprecate approval_token ─────────────────────────────────────────
COMMENT ON COLUMN ops.expense_requests.approval_token IS
  'Magic-link approval token for purchase requests. Generated by '
  'expense-request-notify; consumed by expense-request-decide via anon RLS. '
  'Set only on requests where request_type = purchase_request.';
