-- Seed ops.compliance_postings with the required CA/federal/local workplace postings.
-- Sources verified 2026-08-18 against dir.ca.gov, dol.gov, eeoc.gov, edd.ca.gov,
-- calcivilrights.ca.gov, sos.ca.gov and alamedaca.gov. Applied live.

insert into ops.compliance_postings
(jurisdiction, agency, title, form_code, source_url, applies_when, posted_location, version_label, effective_date, review_by, languages, required, notes)
values
('federal','U.S. DOL Wage & Hour Division','Employee Rights Under the Fair Labor Standards Act (Federal Minimum Wage)','WH1088','https://www.dol.gov/sites/dolgov/files/WHD/legacy/files/minwagep.pdf','All employers covered by the FLSA','Hangar 200 — break room board','REV 04/23',null,null,'English, Spanish',true,'Editions older than the Aug-2016 revision no longer satisfy the requirement. Federal MW is $7.25; the CA state and City of Alameda rates control what we actually pay, but this poster is still separately required.'),
('federal','U.S. DOL Wage & Hour Division','Employee Rights: Employee Polygraph Protection Act','WH 1462','https://www.dol.gov/agencies/whd/posters/employee-polygraph-protection-act','All private employers subject to EPPA (effectively all private employers)','Hangar 200 — break room board','July 2016 or later',null,null,'English, Spanish',true,'Must be displayed prominently where employees AND applicants can readily observe it. Form number is per the DIR postings table; DOL''s own page does not display one.'),
('federal','U.S. EEOC','Know Your Rights: Workplace Discrimination is Illegal','EEOC 22-088','https://www.eeoc.gov/sites/default/files/2023-06/22-088_EEOC_KnowYourRights6.12.pdf','Employers with 15+ employees (Title VII, ADA, GINA); ADEA at 20+','Hangar 200 — break room board','6/2023',null,null,'English, Spanish, Arabic, Chinese, Haitian Creole, Korean, Russian, Tagalog, Vietnamese, Portuguese',true,'Replaced the old "EEO is the Law" poster; the 6/2023 version adds the Pregnant Workers Fairness Act. We are covered at 15-25 employees. Failure to post carries a civil penalty. A digital posting supplements, never replaces, the physical one.'),
('federal','U.S. DOL Veterans'' Employment and Training Service','Your Rights Under USERRA',null,'https://www.dol.gov/sites/dolgov/files/VETS/files/USERRA-Poster.pdf','All employers, regardless of size','Hangar 200 — break room board',null,null,null,'English, Spanish',true,'38 U.S.C. 4334. DOL permits posting where employee notices are customarily placed, OR distribution by mail/hand/email so long as the full text reaches employees. Not listed on the DIR California table — standalone federal duty.'),
('federal','U.S. DOL Wage & Hour Division','Employee Rights Under the Family and Medical Leave Act','WH 1420','https://www.dol.gov/agencies/whd/posters/fmla','Employers with 50+ employees within 75 miles','Not posted — below threshold',null,null,null,'English, Spanish',false,'NOT APPLICABLE at our headcount. Post only if we reach 50 employees. California CFRA (5+ employees) DOES apply to us and is covered by the separate CRD CFRA/PDL notice.'),
('state','CA Industrial Welfare Commission / DIR','IWC Wage Order (industry- or occupation-specific)','Order 1, 7, or 9 — MUST BE CONFIRMED','https://www.dir.ca.gov/IWC/WageOrderIndustries.htm','All employers — post the ONE order matching the business''s principal purpose','Hangar 200 — next to the MW-2026 notice',null,null,null,'English, Spanish',true,'OPEN ITEM — confirm with DLSE before printing. Order 1 Manufacturing indexes "Bottling (soft drinks)"; Order 7 Mercantile indexes "Wholesale houses"; Order 9 Transportation covers firms in the business of transport/warehousing FOR OTHERS (our own delivery drivers do not by themselves pull us in). DIR''s rule is the principal purpose of the business — only one order applies unless operations are separately managed at all levels. Classification guide: https://www.dir.ca.gov/dlse/whichiwcorderclassifications.pdf'),
('state','CA Industrial Welfare Commission / DIR','California Minimum Wage — Official Notice','MW-2026','https://www.dir.ca.gov/iwc/MW-2026.pdf','Every employer, regardless of number of employees','Hangar 200 — next to the IWC wage order','MW-2026','2026-01-01','2027-01-01','English, Spanish',true,'State minimum wage $16.90/hr effective 1/1/2026 (was $16.50). The poster instructs: POST NEXT TO YOUR IWC INDUSTRY OR OCCUPATION ORDER. Also carries the meals-and-lodging credit table. The City of Alameda rate is higher and is what we actually pay. Swap this poster each January.'),
('state','CA Labor Commissioner (DLSE)','Payday Notice',null,'https://www.dir.ca.gov/dlse/PaydayNotice.pdf','All employers (Labor Code 207)','Hangar 200 — break room board',null,null,null,'English, Spanish',true,'Fill-in poster. We must write in our actual regular paydays, time, and place of payment — an unfilled poster does not satisfy the requirement.'),
('state','CA Labor Commissioner (DLSE)','Healthy Workplaces / Healthy Families Act — California Paid Sick Leave',null,'https://www.dir.ca.gov/DLSE/Publications/Paid_Sick_Days_Poster_Template_(11_2014).pdf','All employers (Labor Code 247)','Hangar 200 — break room board','as amended effective 1/1/2026','2026-01-01',null,'English, Spanish',true,'The hosted file keeps a legacy 2014 filename but the current content is captioned "as amended effective 1/1/2026". Confirm the board copy carries that caption.'),
('state','CA Labor Commissioner (DLSE)','Whistleblowers Are Protected',null,'https://www.dir.ca.gov/dlse/WhistleblowersNotice.pdf','All employers (Labor Code 1102.8(a)-(b))','Hangar 200 — break room board','AB 2299 model, eff. 1/1/2025','2025-01-01',null,'English, Spanish',true,'FORMATTING RULE printed on the document: must be on 8.5 x 14 LEGAL paper with margins no larger than one-half inch, so the lettering exceeds the 14-point type the statute requires. A letter-size printout is non-compliant.'),
('state','CA Labor Commissioner (DLSE)','California Workplace — Know Your Rights',null,'https://www.dir.ca.gov/dlse/Know-Your-Rights-Notice/Know-Your-Rights-Notice-English.pdf','All employers','Board + individually distributed to every employee','SB 294, eff. 1/1/2026','2026-01-01','2027-02-01','English, Spanish, Chinese (simp/trad), Vietnamese, Korean, Tagalog, Hindi, Punjabi, Arabic, Urdu',true,'NEW for 2026 and this is a DISTRIBUTION duty, not just a posting. SB 294 Workplace Know Your Rights Act, Labor Code 1550-1559: provide the notice to every employee on or before February 1, 2026 and annually thereafter, in the language we normally use with that employee. Penalty up to $500 per employee. SB 294 also requires notifying an employee''s designated emergency contact if they are arrested or detained at the worksite. Post it as well — DIR lists it on the postings page.'),
('state','Cal/OSHA','Safety and Health Protection on the Job',null,'https://www.dir.ca.gov/dosh/dosh_publications/shpstreng012000.pdf','All employers (Labor Code 6328)','Hangar 200 — break room board',null,null,null,'English, Spanish',true,'California''s state-plan equivalent of the federal OSHA 3165 poster. Cal/OSHA is a state plan, so THIS version — not the federal one — is what a California worksite must post.'),
('state','Cal/OSHA','Emergency Phone Numbers','S-500','https://www.dir.ca.gov/dosh/dosh_publications/s500pstr.pdf','All employers, per the DIR workplace-postings list','Hangar 200 — board + CO2 fill station',null,null,null,'English',true,'Fill-in poster: ambulance, fire/rescue, hospital, physician, alternate, police, Cal/OSHA. Populate it from the Dashboard contact list. Note the authority printed on the poster (8 CCR 1512(e)) sits in the Construction Safety Orders, but DIR lists it under all employers — post it regardless given the CO2 hazard.'),
('state','Cal/OSHA','Access to Medical and Exposure Records',null,'https://www.dir.ca.gov/dosh/dosh_publications/Access_En.pdf','All employers using hazardous or toxic substances','Hangar 200 — break room board',null,null,null,'English, Spanish',true,'8 CCR 3204. APPLIES TO US — we handle CO2 and maintain an SDS library, which puts us squarely in "employers using hazardous or toxic substances".'),
('state','Cal/OSHA','Operating Rules for Industrial Trucks',null,'https://www.dir.ca.gov/dosh/dosh_publications/IndTrucks_Eng.pdf','Employers operating forklifts and other industrial trucks','Hangar 200 — warehouse / forklift area',null,null,null,'English, Spanish',true,'8 CCR 3664. APPLIES — we run forklifts. This posting is separate from, and does not substitute for, operator certification and the 3-year re-evaluation (see handbook Part E).'),
('state','Cal/OSHA','Form 300A — Annual Summary of Work-Related Injuries and Illnesses','Cal/OSHA Form 300A (Appendix B)','https://www.dir.ca.gov/dosh/doshreg/apndxb300afinal.pdf','Employers with 11+ employees in the previous calendar year, unless NAICS-exempt','Hangar 200 — break room board, Feb 1 to Apr 30',null,null,'2027-02-01','English',true,'SEASONAL: post February 1 through April 30 each year covering the prior calendar year. APPLIES TO US — above the 10-or-fewer exemption, and neither beverage manufacturing (3121), beverage/grocery wholesalers (4244/4248), nor warehousing (4931) is on the 8 CCR 14300.2 Appendix A exempt list. Post even with zero injuries; do not alter, deface, or cover it. Must be presented or mailed to any employee paid during Feb-Apr who does not report at least weekly to the posting location — that is our route drivers and field techs.'),
('state','CA Division of Workers'' Compensation','Notice to Employees — Injuries Caused by Work','DWC 7 (10/2024)','https://www.dir.ca.gov/dwc/NoticePoster.pdf','All employers (8 CCR 9881)','Hangar 200 — break room board','DWC 7 (10/2024)','2024-10-01',null,'Bilingual English/Spanish in one document',true,'Fill in the claims administrator name, our workers'' comp insurer, phone, and the nearest Information & Assistance Officer. Covers predesignation of a personal physician and references MPN/HCO treatment. Our carrier: AmTrust / Security National (NAIC 19879) via Embroker, policy SWC1470931.'),
('state','CA DWC / our claims administrator','Notice of Workers'' Compensation Carrier and Coverage',null,'https://www.dir.ca.gov/wpnodb.html','All employers (Labor Code 3550)','Hangar 200 — break room board',null,null,'2027-01-01','English, Spanish',true,'No state-published PDF — obtain the form from AmTrust / Embroker. Must name the CURRENT carrier; update it at every renewal (ours renews 1/1).'),
('state','CA Employment Development Department','Notice to Employees — Unemployment Insurance, State Disability Insurance, Paid Family Leave','DE 1857A (Rev. 45)','https://edd.ca.gov/siteassets/files/pdf_pub_ctr/de1857a.pdf','All employers','Hangar 200 — break room board','Rev. 45',null,null,'English, Spanish',true,'Separate from the individual EDD handouts we must GIVE employees: DE 2515 (Disability Insurance Provisions) and DE 2511 (Paid Family Leave) at hire/onset of leave, and DE 2320 (For Your Benefit) at separation. Those are distributions, not postings.'),
('state','CA Employment Development Department','Notice to Employees — Unemployment Insurance Benefits','DE 1857D (Rev. 19)','https://edd.ca.gov/siteassets/files/pdf_pub_ctr/de1857d.pdf','All employers','Hangar 200 — break room board','Rev. 19',null,null,'English, Spanish',true,null),
('state','CA Civil Rights Department','California Law Prohibits Workplace Discrimination and Harassment','CRD-E07P-ENG','https://calcivilrights.ca.gov/wp-content/uploads/sites/32/2023/01/Workplace-Discrimination-Poster_ENG.pdf','All employers must post; discrimination provisions cover 5+ employees','Hangar 200 — break room board',null,null,null,'English, Spanish and others via CRD',true,'2 CCR 11023 requires ALL employers to post this. APPLIES — we are above 5 employees.'),
('state','CA Civil Rights Department','Sexual Harassment (poster / fact sheet)','CRD-185P-ENG','https://calcivilrights.ca.gov/wp-content/uploads/sites/32/2022/12/Sexual-Harassment-Poster_ENG.pdf','All employers, regardless of the number of employees','Board + distributed to employees',null,null,null,'English, Spanish and others via CRD',true,'CRD accepts either this poster or the equivalent fact sheet, and the information must ALSO be distributed to employees. Separately, at 5+ employees we owe biennial sexual-harassment prevention training (2 hrs supervisors / 1 hr non-supervisors) — a training duty, not a posting.'),
('state','CA Civil Rights Department','Family Care and Medical Leave (CFRA) and Pregnancy Disability Leave','CRD-100-21ENG','https://calcivilrights.ca.gov/wp-content/uploads/sites/32/2023/01/CFRA-and-Pregnancy-Leave_ENG.pdf','Employers with 5+ employees','Board + distributed to employees',null,null,null,'English, Spanish and others via CRD',true,'APPLIES — CFRA has covered 5+ employee employers since 2021, so we owe CFRA even though federal FMLA (50+) does not reach us. Must be posted AND distributed. If a significant share of the workforce speaks another language, CRD requires translation.'),
('state','CA Civil Rights Department','Your Rights and Obligations as a Pregnant Employee','CRD-E09P-ENG','https://calcivilrights.ca.gov/wp-content/uploads/sites/32/2023/01/Your-Rights-and-Obligations-as-a-Pregnant-Employee_ENG.pdf','Employers with 5+ employees','Hangar 200 — break room board',null,null,null,'English, Spanish and others via CRD',true,'APPLIES. Must also be given directly to an employee who notifies us of a pregnancy.'),
('state','CA Civil Rights Department','The Rights of Employees who are Transgender or Gender Nonconforming','CRD-E04P-ENG','https://calcivilrights.ca.gov/wp-content/uploads/sites/32/2022/11/The-Rights-of-Employees-who-are-Transgender-or-Gender-Nonconforming-Poster_ENG.pdf','All employers (harassment); 5+ employees (discrimination)','Hangar 200 — break room board',null,'2018-01-01',null,'English, Spanish and others via CRD',true,'Mandatory posting since January 1, 2018.'),
('state','CA Civil Rights Department','Survivors of Violence and Family Members of Victims — Right to Time Off and Accommodations',null,'https://calcivilrights.ca.gov/wp-content/uploads/sites/32/2025/07/Survivors-Right-to-Time-Off_English-B.pdf','All employers must provide the notice; some time-off rights apply only at 25+ employees','Distributed — at hire, annually, on request','AB 2499, eff. 1/1/2025','2025-01-01',null,'English, Spanish',true,'DISTRIBUTION duty, not a posting. Provide when hired, annually, on request, and to any worker who discloses being a victim. Moved from Labor Code 230.1 to FEHA/CRD by AB 2499. OPEN ITEM: the notice references a 25-or-more-worker threshold for some entitlements — confirm which pieces bind at our headcount.'),
('state','CA Labor Commissioner (DLSE)','Notice of Inspection by Immigration Agencies',null,'https://www.dir.ca.gov/DLSE/LC_90.2_EE_Notice.pdf','All employers — EVENT-DRIVEN, not a standing posting','Held on file — post within 72 hours if triggered',null,null,null,'English, Spanish',true,'Labor Code 90.2(a). Triggered only when we receive notice of an upcoming immigration-agency inspection of I-9s or other employment records. Then post within 72 hours, to employees and any union representative. Keep the template on file, not on the board.'),
('state','CA Secretary of State','Time Off to Vote notice',null,'https://elections.cdn.sos.ca.gov/pdfs/tov-english.pdf','All employers — SEASONAL, 10 days before each statewide election','Board or where employees enter/exit — from ~Oct 24, 2026',null,null,'2026-10-24','English, Spanish and others via SOS',true,'Elections Code 14001. Statewide general election is November 3, 2026, so this goes up by about October 24, 2026. Employees get paid time off only if they lack sufficient time outside working hours and give 2 working days'' notice — flag to dispatch because of route drivers.'),
('state','CA (Labor Code 6404.5)','No Smoking signage',null,'https://www.dir.ca.gov/wpnodb.html','All employers','Every entrance and enclosed workspace',null,null,null,'English',true,'Labor Code 6404.5(c)(1). No state-issued PDF — we post our own compliant signage. Current law also covers vaping.'),
('local','City of Alameda — Base Reuse and Economic Development','Official Notice — City of Alameda Minimum Wage Rate',null,'https://www.alamedaca.gov/files/assets/public/v/1/departments/alameda/econ-dev-amp-comm-services/business/minimum-wage/2026-min-wage/2026-notice-english.pdf','Any employer with an employee working 2+ hours in a workweek inside Alameda city limits — no size exemption','Hangar 200 — break room board','2026 notice','2026-07-01','2027-07-01','English, Spanish, Chinese, Korean, Vietnamese, Tagalog, Arabic',true,'CONFIRMED APPLICABLE — Hangar 200 is inside the City of Alameda. Rate $17.76/hour effective July 1, 2026 (was $17.46). AMC Chapter 4-60. CPI-W adjusted every July 1 — next change 7/1/2027, set a reminder to swap the poster. Tips may NOT be credited. Notice must be provided in English and the employee''s preferred language on request. Contact: 950 West Mall Square Rm 205, Alameda CA 94501, (510) 747-6859, minimumwage@alamedaca.gov. Because $17.76 exceeds the $16.90 state rate, the city rate is what we pay — but MW-2026 still gets posted alongside it.');
